name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: update ubuntu
      run: sudo apt update
    - name: install headers
      run: sudo apt install build-essential linux-headers-$(uname -r)
    - name: checkout repo
      uses: actions/checkout@main
      with:
        path: main
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
