name: Build Dummy Driver

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up build environment
      run: sudo apt-get update && sudo apt-get install -y autoconf automake build-essential linux-headers-$(uname -r)
    - name: list
      run: ls -l
    - name: Generate configure script
      run: |
        aclocal
        autoconf
        automake --add-missing
        ./configure
    - name: Build module
      run: make
    - name: Run tests
      run: make check
    - name: Run module install
      run: make install
    - name: Run module uninstall
      run: make uninstall
    - name: Uninstall
      run: make uninstall
